### ISSUE TITLE
Nested commands

### ISSUE THREAD

**Issue by bozhidarc** [Cilex/Cilex#73]
Hi,
Is there a way to call one command from another or to create a batch of commands?

**Comment by kamilsk** [comment]
Hi, @bozhidarc!

I used the following approach to a similar task:
https://github.com/kamilsk/CilexServiceProviders/blob/master/docs/AppAndCommands.md#presetcommand
https://github.com/kamilsk/CilexServiceProviders/blob/master/src/Command/PresetCommand.php#L101-L115

You can improve this solution for your task.
